channels:
  - conda-canary
  - defaults
dependencies:
  - pip=22.2.2
  - python=3.9
  - pip:
    - datasets==2.7.1
    - huggingface-hub==0.24.0
    - jsonlines==3.1.0
    - numpy==2.0.1
    - openai==0.23.1
    - pandas==2.2.2
    - pddl==0.2.0
    - regex==2022.10.31
    - scikit-learn==1.5.1
    - scipy==1.13.1
    - tenacity==8.1.0
    - tiktoken==0.4.0
    - tokenizers==0.13.2
    - tqdm==4.64.1
    - transformers==4.25.1
    - uncertainty-calibration==0.1.4
    - vllm==0.5.0.post1
    - vllm-flash-attn==2.5.9